// Generated by scripts/build-classic-worker.mjs. Do not edit directly.
// The separate scopes preserve the trusted modules' bindings without changing their source.
(() => {
"use strict";
const { serializedJsonByteLength } = (() => {
const NativeArray = Array;
const NativeError = Error;
const NativeNumber = Number;
const NativeSet = Set;
const NativeString = String;
const NativeTextEncoder = TextEncoder;
const NativeTypeError = TypeError;
const NativeWeakMap = WeakMap;
const NativeWeakSet = WeakSet;
const nativeObjectPrototype = Object.prototype;
const uncurryThis = (method) => Function.prototype.call.bind(method);
const arrayIsArray = Array.isArray.bind(Array);
const arrayJoin = uncurryThis(Array.prototype.join);
const arrayPop = uncurryThis(Array.prototype.pop);
const arrayPush = uncurryThis(Array.prototype.push);
const arraySort = uncurryThis(Array.prototype.sort);
const jsonStringify = JSON.stringify.bind(JSON);
const mathMin = Math.min.bind(Math);
const numberIsFinite = Number.isFinite.bind(Number);
const numberIsInteger = Number.isInteger.bind(Number);
const numberIsSafeInteger = Number.isSafeInteger.bind(Number);
const objectCreate = Object.create.bind(Object);
const objectDefineProperty = Object.defineProperty.bind(Object);
const objectFreeze = Object.freeze.bind(Object);
const objectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor.bind(Object);
const objectGetPrototypeOf = Object.getPrototypeOf.bind(Object);
const objectHasOwn = Object.hasOwn.bind(Object);
const objectKeys = Object.keys.bind(Object);
const objectSetPrototypeOf = Object.setPrototypeOf.bind(Object);
const objectValues = Object.values.bind(Object);
const reflectOwnKeys = Reflect.ownKeys.bind(Reflect);
const regexpExec = uncurryThis(RegExp.prototype.exec);
const setAdd = uncurryThis(Set.prototype.add);
const setHas = uncurryThis(Set.prototype.has);
const stringTrim = uncurryThis(String.prototype.trim);
const weakMapGet = uncurryThis(WeakMap.prototype.get);
const weakMapHas = uncurryThis(WeakMap.prototype.has);
const weakMapSet = uncurryThis(WeakMap.prototype.set);
const weakSetAdd = uncurryThis(WeakSet.prototype.add);
const weakSetDelete = uncurryThis(WeakSet.prototype.delete);
const weakSetHas = uncurryThis(WeakSet.prototype.has);
const textEncoder = new NativeTextEncoder();
const encodeText = NativeTextEncoder.prototype.encode.bind(textEncoder);
const typedArrayPrototype = objectGetPrototypeOf(Uint8Array.prototype);
const typedArrayByteLength = uncurryThis(
  objectGetOwnPropertyDescriptor(typedArrayPrototype, "byteLength").get,
);

function defineDataProperty(target, key, value) {
  const descriptor = objectCreate(null);
  descriptor.value = value;
  descriptor.enumerable = true;
  descriptor.configurable = true;
  descriptor.writable = true;
  return objectDefineProperty(target, key, descriptor);
}

const KIBIBYTE = 1024;

const DEFAULT_EXECUTION_LIMITS = objectFreeze({
  maxSourceBytes: 20 * KIBIBYTE,
  maxTests: 20,
  maxInputBytesPerTest: 16 * KIBIBYTE,
  maxOutputBytesPerTest: 16 * KIBIBYTE,
  maxConsoleEntries: 100,
  maxConsoleBytes: 8 * KIBIBYTE,
  testTimeoutMs: 1000,
  runTimeoutMs: 5000,
  maxRunsPerWindow: 20,
  runWindowMs: 60_000,
});

const GRADING_OUTCOMES = objectFreeze({
  PASSED: "passed",
  WRONG_ANSWER: "wrong_answer",
  SYNTAX_ERROR: "syntax_error",
  RUNTIME_ERROR: "runtime_error",
  TIMEOUT: "timeout",
  OUTPUT_LIMIT: "output_limit",
  CANCELLED: "cancelled",
  ENGINE_ERROR: "engine_error",
  NOT_RUN: "not_run",
});

const REQUEST_FIELD_NAMES = objectFreeze([
  "requestId",
  "contractVersion",
  "questId",
  "questRevision",
  "languageId",
  "suite",
  "source",
  "entryPoint",
  "tests",
]);
const REQUEST_FIELDS = new NativeSet(REQUEST_FIELD_NAMES);
const TEST_REQUIRED_FIELD_NAMES = objectFreeze(["id", "args", "expected"]);
const TEST_OPTIONAL_FIELD_NAMES = objectFreeze(["label"]);
const TEST_FIELDS = new NativeSet([
  ...TEST_REQUIRED_FIELD_NAMES,
  ...TEST_OPTIONAL_FIELD_NAMES,
]);
const LIMIT_FIELD_NAMES = objectFreeze(objectKeys(DEFAULT_EXECUTION_LIMITS));
const LIMIT_FIELDS = new NativeSet(LIMIT_FIELD_NAMES);
const OUTCOME_NAMES = objectFreeze(objectValues(GRADING_OUTCOMES));
const OUTCOME_VALUES = new NativeSet(OUTCOME_NAMES);
const STABLE_ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ENTRY_POINT_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const RESERVED_ENTRY_POINTS = new NativeSet([
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "implements",
  "import",
  "in",
  "instanceof",
  "interface",
  "let",
  "new",
  "null",
  "package",
  "private",
  "protected",
  "public",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);
const OVERALL_OUTCOME_PRIORITY = [
  GRADING_OUTCOMES.CANCELLED,
  GRADING_OUTCOMES.ENGINE_ERROR,
  GRADING_OUTCOMES.TIMEOUT,
  GRADING_OUTCOMES.OUTPUT_LIMIT,
  GRADING_OUTCOMES.SYNTAX_ERROR,
  GRADING_OUTCOMES.RUNTIME_ERROR,
  GRADING_OUTCOMES.WRONG_ANSWER,
  GRADING_OUTCOMES.NOT_RUN,
];
// 루트 컨테이너를 깊이 0으로 세며, 0..511의 컨테이너를 허용한다.
// javascript-runtime.js의 반환값 정규화와 같은 경계여야 한다.
const MAX_JSON_CONTAINER_DEPTH = 512;
const MAX_SAFE_JSON_BYTES = NativeNumber.MAX_SAFE_INTEGER;

function isPlainRecord(value) {
  if (value === null || typeof value !== "object" || arrayIsArray(value)) return false;

  try {
    const prototype = objectGetPrototypeOf(value);
    return prototype === nativeObjectPrototype || prototype === null;
  } catch {
    return false;
  }
}

function isNonEmptyString(value) {
  return typeof value === "string" && stringTrim(value).length > 0;
}

function appendJsonPath(path, key) {
  if (regexpExec(/^[A-Za-z_$][A-Za-z0-9_$]*$/, key) !== null) return `${path}.${key}`;
  return `${path}[${jsonStringify(key)}]`;
}

function findJsonValueIssue(rootValue, rootPath) {
  const activeObjects = new NativeWeakSet();
  const validatedDepths = new NativeWeakMap();
  const stack = [{ kind: "visit", value: rootValue, path: rootPath, depth: 0 }];

  try {
    while (stack.length > 0) {
      const frame = arrayPop(stack);
      if (frame.kind === "exit") {
        weakSetDelete(activeObjects, frame.value);
        const previousDepth = weakMapGet(validatedDepths, frame.value);
        if (!weakMapHas(validatedDepths, frame.value) || frame.depth > previousDepth) {
          weakMapSet(validatedDepths, frame.value, frame.depth);
        }
        continue;
      }

      const { value, path, depth } = frame;
      if (value === null || typeof value === "string" || typeof value === "boolean") {
        continue;
      }
      if (typeof value === "number") {
        if (!numberIsFinite(value)) {
          return `${path}에는 NaN이나 Infinity가 아닌 유한한 number가 필요합니다.`;
        }
        continue;
      }
      if (typeof value !== "object") {
        return `${path}의 ${typeof value} 값은 JSON으로 표현할 수 없습니다.`;
      }
      if (depth >= MAX_JSON_CONTAINER_DEPTH) {
        return `${path}의 JSON 값이 지나치게 깊게 중첩되어 있습니다.`;
      }
      if (weakSetHas(activeObjects, value)) {
        return `${path}에 순환 참조가 있어 JSON으로 표현할 수 없습니다.`;
      }
      const validatedDepth = weakMapGet(validatedDepths, value);
      if (weakMapHas(validatedDepths, value) && depth <= validatedDepth) {
        continue;
      }

      weakSetAdd(activeObjects, value);
      arrayPush(stack, { kind: "exit", value, depth });

      if (arrayIsArray(value)) {
        const lengthDescriptor = objectGetOwnPropertyDescriptor(value, "length");
        const length = lengthDescriptor?.value;
        if (!numberIsSafeInteger(length) || length < 0 || length > 0xffff_ffff) {
          return `${path} 배열의 length를 안전하게 검사할 수 없습니다.`;
        }
        const indexEntries = [];
        const ownKeys = reflectOwnKeys(value);
        for (let keyIndex = 0; keyIndex < ownKeys.length; keyIndex += 1) {
          const key = ownKeys[keyIndex];
          if (key === "length") continue;
          if (typeof key === "symbol") {
            return `${path} 배열의 Symbol 속성은 JSON으로 표현할 수 없습니다.`;
          }

          const index = NativeNumber(key);
          if (
            !numberIsSafeInteger(index) ||
            index < 0 ||
            index >= length ||
            NativeString(index) !== key
          ) {
            return `${path} 배열에 JSON 배열 항목이 아닌 속성 ${jsonStringify(key)}이 있습니다.`;
          }

          const descriptor = objectGetOwnPropertyDescriptor(value, key);
          if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) {
            return `${path}[${index}]은 getter, setter 또는 숨겨진 속성이 아닌 값이어야 합니다.`;
          }
          arrayPush(indexEntries, { index, value: descriptor.value });
        }

        arraySort(indexEntries, (left, right) => left.index - right.index);
        if (indexEntries.length !== length) {
          let missingIndex = 0;
          while (
            missingIndex < indexEntries.length &&
            indexEntries[missingIndex].index === missingIndex
          ) {
            missingIndex += 1;
          }
          return `${path}[${missingIndex}]은 비어 있는 배열 항목이어서 JSON 값이 아닙니다.`;
        }

        for (let index = indexEntries.length - 1; index >= 0; index -= 1) {
          const entry = indexEntries[index];
          arrayPush(stack, {
            kind: "visit",
            value: entry.value,
            path: `${path}[${entry.index}]`,
            depth: depth + 1,
          });
        }
        continue;
      }

      const prototype = objectGetPrototypeOf(value);
      if (prototype !== nativeObjectPrototype && prototype !== null) {
        return `${path}에는 일반 객체, 배열 또는 JSON 기본값만 사용할 수 있습니다.`;
      }

      const entries = [];
      const ownKeys = reflectOwnKeys(value);
      for (let keyIndex = 0; keyIndex < ownKeys.length; keyIndex += 1) {
        const key = ownKeys[keyIndex];
        if (typeof key === "symbol") {
          return `${path} 객체의 Symbol 키는 JSON으로 표현할 수 없습니다.`;
        }
        const descriptor = objectGetOwnPropertyDescriptor(value, key);
        if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) {
          return `${appendJsonPath(path, key)}은 getter, setter 또는 숨겨진 속성이 아닌 값이어야 합니다.`;
        }
        arrayPush(entries, { key, value: descriptor.value });
      }

      for (let index = entries.length - 1; index >= 0; index -= 1) {
        const entry = entries[index];
        arrayPush(stack, {
          kind: "visit",
          value: entry.value,
          path: appendJsonPath(path, entry.key),
          depth: depth + 1,
        });
      }
    }
  } catch {
    return `${rootPath} 값을 안전하게 검사할 수 없습니다.`;
  }

  return null;
}

function serializeJsonValueSafely(value, space) {
  const issue = findJsonValueIssue(value, "JSON 값");
  if (issue) throw new NativeTypeError(issue);
  const safeValue = cloneJsonValueFromDescriptors(
    value,
    "JSON 값",
    new NativeWeakMap(),
    new NativeWeakSet(),
    true,
  );
  return jsonStringify(safeValue, null, space);
}

function serializedJsonByteLength(value, optionalMaxBytes) {
  if (
    optionalMaxBytes !== undefined &&
    (!numberIsSafeInteger(optionalMaxBytes) || optionalMaxBytes < 0)
  ) {
    return null;
  }

  try {
    const issue = findJsonValueIssue(value, "JSON 값");
    if (issue) return null;
    return measureSerializedJsonByteLength(value, optionalMaxBytes);
  } catch {
    return null;
  }
}

function primitiveSerializedByteLength(value) {
  if (value !== null && typeof value === "object") return null;
  const serialized = jsonStringify(value);
  return typeof serialized === "string" ? utf8ByteLength(serialized) : null;
}

function measureSerializedJsonByteLength(rootValue, optionalMaxBytes) {
  const maxBytes = optionalMaxBytes ?? MAX_SAFE_JSON_BYTES;
  const exceededBytes = maxBytes < MAX_SAFE_JSON_BYTES ? maxBytes + 1 : null;
  const primitiveBytes = primitiveSerializedByteLength(rootValue);
  if (primitiveBytes !== null) {
    if (primitiveBytes <= maxBytes) return primitiveBytes;
    return exceededBytes;
  }
  if (rootValue === null || typeof rootValue !== "object") return null;

  const measuredBytes = new NativeWeakMap();
  const activeObjects = new NativeWeakSet();
  const stack = [{ kind: "visit", value: rootValue }];

  while (stack.length > 0) {
    const frame = arrayPop(stack);
    if (frame.kind === "finish") {
      weakSetDelete(activeObjects, frame.value);
      let totalBytes = frame.baseBytes;

      for (let index = 0; index < frame.children.length; index += 1) {
        const child = frame.children[index];
        const childBytes =
          child !== null && typeof child === "object"
            ? weakMapGet(measuredBytes, child)
            : primitiveSerializedByteLength(child);
        if (!numberIsSafeInteger(childBytes) || childBytes < 0) return null;
        if (childBytes > maxBytes - totalBytes) return exceededBytes;
        totalBytes += childBytes;
      }

      weakMapSet(measuredBytes, frame.value, totalBytes);
      continue;
    }

    const current = frame.value;
    if (weakMapHas(measuredBytes, current)) continue;
    if (weakSetHas(activeObjects, current)) return null;
    weakSetAdd(activeObjects, current);

    const children = [];
    let baseBytes = 2;
    if (arrayIsArray(current)) {
      const lengthDescriptor = objectGetOwnPropertyDescriptor(current, "length");
      const length = lengthDescriptor?.value;
      if (!numberIsSafeInteger(length) || length < 0) return null;
      if (length > 0) baseBytes += length - 1;

      for (let index = 0; index < length; index += 1) {
        const descriptor = objectGetOwnPropertyDescriptor(current, NativeString(index));
        if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) return null;
        arrayPush(children, descriptor.value);
      }
    } else {
      const prototype = objectGetPrototypeOf(current);
      if (prototype !== nativeObjectPrototype && prototype !== null) return null;
      const keys = objectKeys(current);
      if (keys.length > 0) baseBytes += keys.length - 1;

      for (let index = 0; index < keys.length; index += 1) {
        const key = keys[index];
        const descriptor = objectGetOwnPropertyDescriptor(current, key);
        if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) return null;
        const keyBytes = primitiveSerializedByteLength(key);
        if (!numberIsSafeInteger(keyBytes)) return null;
        if (keyBytes + 1 > maxBytes - baseBytes) return exceededBytes;
        baseBytes += keyBytes + 1;
        arrayPush(children, descriptor.value);
      }
    }

    if (baseBytes > maxBytes) return exceededBytes;
    arrayPush(stack, { kind: "finish", value: current, children, baseBytes });
    for (let index = children.length - 1; index >= 0; index -= 1) {
      const child = children[index];
      if (
        child !== null &&
        typeof child === "object" &&
        !weakMapHas(measuredBytes, child)
      ) {
        arrayPush(stack, { kind: "visit", value: child });
      }
    }
  }

  const totalBytes = weakMapGet(measuredBytes, rootValue);
  return numberIsSafeInteger(totalBytes) ? totalBytes : null;
}

function inspectDtoFields(value, label, allowedFields, requiredFieldNames, errors) {
  const fieldValues = objectCreate(null);
  let fields;
  try {
    fields = reflectOwnKeys(value);
  } catch {
    arrayPush(errors, `${label}의 필드를 안전하게 확인할 수 없습니다.`);
    return fieldValues;
  }

  const unknownFields = [];
  for (let index = 0; index < fields.length; index += 1) {
    const field = fields[index];
    if (typeof field === "symbol") {
      arrayPush(errors, `${label}에는 Symbol 필드를 사용할 수 없습니다.`);
      continue;
    }
    if (!setHas(allowedFields, field)) {
      arrayPush(unknownFields, field);
      continue;
    }
    const descriptor = objectGetOwnPropertyDescriptor(value, field);
    if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) {
      arrayPush(
        errors,
        `${label}.${field}는 getter, setter 또는 숨겨진 필드가 아닌 값이어야 합니다.`,
      );
      continue;
    }
    defineDataProperty(fieldValues, field, descriptor.value);
  }

  if (unknownFields.length > 0) {
    const message =
      label === "실행 제한 설정"
        ? `허용되지 않은 실행 제한이 있습니다: ${arrayJoin(unknownFields, ", ")}`
        : `${label}에 허용되지 않은 필드가 있습니다: ${arrayJoin(unknownFields, ", ")}`;
    arrayPush(errors, message);
  }

  for (let index = 0; index < requiredFieldNames.length; index += 1) {
    const field = requiredFieldNames[index];
    if (!objectHasOwn(fieldValues, field)) {
      arrayPush(
        errors,
        `${label}.${field}는 필수 own enumerable data 필드여야 합니다.`,
      );
    }
  }
  return fieldValues;
}

function resolveExecutionLimits(overrides, errors) {
  if (overrides === undefined) return DEFAULT_EXECUTION_LIMITS;
  if (!isPlainRecord(overrides)) {
    arrayPush(errors, "실행 제한 설정은 일반 객체여야 합니다.");
    return DEFAULT_EXECUTION_LIMITS;
  }

  const fields = inspectDtoFields(
    overrides,
    "실행 제한 설정",
    LIMIT_FIELDS,
    [],
    errors,
  );

  const resolved = { ...DEFAULT_EXECUTION_LIMITS };
  for (let index = 0; index < LIMIT_FIELD_NAMES.length; index += 1) {
    const field = LIMIT_FIELD_NAMES[index];
    if (!objectHasOwn(fields, field)) continue;
    const value = fields[field];
    if (!numberIsSafeInteger(value) || value <= 0) {
      arrayPush(errors, `실행 제한 ${field}은 0보다 큰 안전한 정수여야 합니다.`);
      continue;
    }
    resolved[field] = value;
  }
  return resolved;
}

function validateExecutionRequestInternal(request, limitOverrides) {
  const errors = [];
  const limits = resolveExecutionLimits(limitOverrides, errors);

  if (!isPlainRecord(request)) {
    arrayPush(errors, "코드 실행 요청은 일반 객체여야 합니다.");
    return errors;
  }
  const requestFields = inspectDtoFields(
    request,
    "코드 실행 요청",
    REQUEST_FIELDS,
    REQUEST_FIELD_NAMES,
    errors,
  );

  if (
    !isNonEmptyString(requestFields.requestId) ||
    regexpExec(STABLE_ID_PATTERN, requestFields.requestId) === null
  ) {
    arrayPush(
      errors,
      "requestId 형식이 올바르지 않습니다. 영문 소문자와 숫자를 하이픈으로 연결해 주세요.",
    );
  }
  if (requestFields.contractVersion !== 1) {
    arrayPush(errors, "지원하는 contractVersion은 1입니다.");
  }
  if (
    !isNonEmptyString(requestFields.questId) ||
    regexpExec(STABLE_ID_PATTERN, requestFields.questId) === null
  ) {
    arrayPush(
      errors,
      "questId 형식이 올바르지 않습니다. 영문 소문자와 숫자를 하이픈으로 연결해 주세요.",
    );
  }
  if (!numberIsSafeInteger(requestFields.questRevision) || requestFields.questRevision <= 0) {
    arrayPush(errors, "questRevision은 1 이상의 안전한 정수여야 합니다.");
  }
  if (requestFields.languageId !== "javascript") {
    arrayPush(errors, 'languageId는 "javascript"여야 합니다.');
  }
  if (requestFields.suite !== "public") {
    arrayPush(errors, 'suite는 "public"이어야 합니다.');
  }

  if (!isNonEmptyString(requestFields.source)) {
    arrayPush(errors, "source는 비어 있지 않은 문자열이어야 합니다.");
  } else {
    const sourceBytes = utf8ByteLength(requestFields.source);
    if (sourceBytes > limits.maxSourceBytes) {
      arrayPush(
        errors,
        `source의 UTF-8 크기는 ${limits.maxSourceBytes}바이트 이하여야 합니다. ` +
          `(현재 ${sourceBytes}바이트)`,
      );
    }
  }

  if (
    !isNonEmptyString(requestFields.entryPoint) ||
    regexpExec(ENTRY_POINT_PATTERN, requestFields.entryPoint) === null ||
    setHas(RESERVED_ENTRY_POINTS, requestFields.entryPoint)
  ) {
    arrayPush(errors, "entryPoint는 예약어가 아닌 안정적인 ASCII JavaScript 식별자여야 합니다.");
  }

  const tests = requestFields.tests;
  if (!arrayIsArray(tests)) {
    arrayPush(errors, "tests에는 한 개 이상의 공개 테스트가 필요합니다.");
    return errors;
  }
  const testsLengthDescriptor = objectGetOwnPropertyDescriptor(tests, "length");
  const testsLength = testsLengthDescriptor?.value;
  if (
    !testsLengthDescriptor ||
    !objectHasOwn(testsLengthDescriptor, "value") ||
    !numberIsSafeInteger(testsLength) ||
    testsLength < 0 ||
    testsLength > 0xffff_ffff
  ) {
    arrayPush(errors, "tests 배열의 length를 안전하게 확인할 수 없습니다.");
    return errors;
  }
  if (testsLength === 0) {
    arrayPush(errors, "tests에는 한 개 이상의 공개 테스트가 필요합니다.");
    return errors;
  }
  if (testsLength > limits.maxTests) {
    arrayPush(errors, `tests는 최대 ${limits.maxTests}개까지 실행할 수 있습니다.`);
  }

  const testIds = new NativeSet();
  const testCountToInspect = mathMin(testsLength, limits.maxTests);
  for (let index = 0; index < testCountToInspect; index += 1) {
    const label = `tests[${index}]`;
    const testDescriptor = objectGetOwnPropertyDescriptor(tests, NativeString(index));
    if (
      !testDescriptor?.enumerable ||
      !objectHasOwn(testDescriptor, "value")
    ) {
      arrayPush(errors, `${label}은 own enumerable data 배열 항목이어야 합니다.`);
      continue;
    }
    const test = testDescriptor.value;
    if (!isPlainRecord(test)) {
      arrayPush(errors, `${label}은 일반 객체여야 합니다.`);
      continue;
    }
    const testFields = inspectDtoFields(
      test,
      label,
      TEST_FIELDS,
      TEST_REQUIRED_FIELD_NAMES,
      errors,
    );

    if (!isNonEmptyString(testFields.id) || regexpExec(STABLE_ID_PATTERN, testFields.id) === null) {
      arrayPush(
        errors,
        `${label}.id 형식이 올바르지 않습니다. 영문 소문자와 숫자를 하이픈으로 연결해 주세요.`,
      );
    } else if (setHas(testIds, testFields.id)) {
      arrayPush(errors, `공개 테스트 ID가 중복됩니다: ${testFields.id}`);
    } else {
      setAdd(testIds, testFields.id);
    }

    if (objectHasOwn(testFields, "label") && !isNonEmptyString(testFields.label)) {
      arrayPush(errors, `${label}.label은 생략하거나 비어 있지 않은 문자열이어야 합니다.`);
    }

    if (!arrayIsArray(testFields.args)) {
      arrayPush(errors, `${label}.args는 배열이어야 합니다.`);
    } else {
      const argsIssue = findJsonValueIssue(testFields.args, `${label}.args`);
      if (argsIssue) {
        arrayPush(errors, argsIssue);
      } else {
        const inputBytes = serializedJsonByteLength(
          testFields.args,
          limits.maxInputBytesPerTest,
        );
        if (inputBytes === null) {
          arrayPush(errors, `${label}.args를 JSON으로 직렬화할 수 없습니다.`);
        } else if (inputBytes > limits.maxInputBytesPerTest) {
          arrayPush(
            errors,
            `${label}.args의 JSON 크기는 ${limits.maxInputBytesPerTest}바이트 이하여야 합니다. ` +
              `(최소 ${inputBytes}바이트)`,
          );
        }
      }
    }

    const expectedIssue = findJsonValueIssue(testFields.expected, `${label}.expected`);
    if (expectedIssue) {
      arrayPush(errors, expectedIssue);
    } else {
      const outputBytes = serializedJsonByteLength(
        testFields.expected,
        limits.maxOutputBytesPerTest,
      );
      if (outputBytes === null) {
        arrayPush(errors, `${label}.expected를 JSON으로 직렬화할 수 없습니다.`);
      } else if (outputBytes > limits.maxOutputBytesPerTest) {
        arrayPush(
          errors,
          `${label}.expected의 JSON 크기는 ${limits.maxOutputBytesPerTest}바이트 이하여야 합니다. ` +
            `(최소 ${outputBytes}바이트)`,
        );
      }
    }
  }

  return errors;
}

function cloneJsonValueFromDescriptors(
  value,
  path,
  copies,
  activeObjects,
  useNullObjectPrototypes = false,
  useNullArrayPrototypes = useNullObjectPrototypes,
) {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "boolean" ||
    (typeof value === "number" && numberIsFinite(value))
  ) {
    return value;
  }
  if (typeof value !== "object") {
    throw new NativeTypeError(`${path}의 ${typeof value} 값은 JSON으로 복제할 수 없습니다.`);
  }
  if (weakSetHas(activeObjects, value)) {
    throw new NativeTypeError(`${path}에 순환 참조가 있어 JSON으로 복제할 수 없습니다.`);
  }
  if (weakMapHas(copies, value)) return weakMapGet(copies, value);

  const isArray = arrayIsArray(value);
  if (!isArray) {
    const prototype = objectGetPrototypeOf(value);
    if (prototype !== nativeObjectPrototype && prototype !== null) {
      throw new NativeTypeError(`${path}에는 일반 객체, 배열 또는 JSON 기본값만 사용할 수 있습니다.`);
    }
  }

  let copy;
  if (isArray) {
    const lengthDescriptor = objectGetOwnPropertyDescriptor(value, "length");
    const length = lengthDescriptor?.value;
    if (!numberIsInteger(length) || length < 0 || length > 0xffff_ffff) {
      throw new NativeTypeError(`${path} 배열의 length를 안전하게 복제할 수 없습니다.`);
    }
    copy = new NativeArray(length);
    if (useNullArrayPrototypes) objectSetPrototypeOf(copy, null);
  } else {
    copy = useNullObjectPrototypes ? objectCreate(null) : {};
  }

  weakMapSet(copies, value, copy);
  weakSetAdd(activeObjects, value);
  try {
    const ownKeys = reflectOwnKeys(value);
    for (let keyIndex = 0; keyIndex < ownKeys.length; keyIndex += 1) {
      const key = ownKeys[keyIndex];
      if (isArray && key === "length") continue;
      if (typeof key === "symbol") {
        throw new NativeTypeError(`${path}의 Symbol 키는 JSON으로 복제할 수 없습니다.`);
      }

      const descriptor = objectGetOwnPropertyDescriptor(value, key);
      if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) {
        throw new NativeTypeError(
          `${appendJsonPath(path, key)}은 getter, setter 또는 숨겨진 속성이 아닌 값이어야 합니다.`,
        );
      }

      defineDataProperty(
        copy,
        key,
        cloneJsonValueFromDescriptors(
          descriptor.value,
          appendJsonPath(path, key),
          copies,
          activeObjects,
          useNullObjectPrototypes,
          useNullArrayPrototypes,
        ),
      );
    }
  } finally {
    weakSetDelete(activeObjects, value);
  }

  return copy;
}

function deepFreezeDescriptorValue(rootValue) {
  const frozenValues = new NativeWeakSet();

  function freezeValue(value) {
    if (value === null || typeof value !== "object" || weakSetHas(frozenValues, value)) {
      return value;
    }

    weakSetAdd(frozenValues, value);
    const ownKeys = reflectOwnKeys(value);
    for (let keyIndex = 0; keyIndex < ownKeys.length; keyIndex += 1) {
      const descriptor = objectGetOwnPropertyDescriptor(value, ownKeys[keyIndex]);
      if (descriptor && objectHasOwn(descriptor, "value")) freezeValue(descriptor.value);
    }
    return objectFreeze(value);
  }

  return freezeValue(rootValue);
}

function utf8ByteLength(value) {
  if (typeof value !== "string") {
    throw new NativeTypeError("UTF-8 크기를 계산할 문자열이 필요합니다.");
  }
  return typedArrayByteLength(encodeText(value));
}

function formatJsonValue(value) {
  const issue = findJsonValueIssue(value, "값");
  if (!issue) return serializeJsonValueSafely(value, 2);

  if (value === undefined) return "undefined";
  if (typeof value === "number") return NativeString(value);
  if (typeof value === "bigint") return `${value}n`;
  if (typeof value === "symbol") return NativeString(value);
  if (typeof value === "function") {
    return `[Function${value.name ? `: ${value.name}` : ""}]`;
  }
  return `[JSON으로 표시할 수 없는 값: ${issue}]`;
}

function areJsonValuesEqual(left, right) {
  if (findJsonValueIssue(left, "left") || findJsonValueIssue(right, "right")) {
    return false;
  }

  const stack = [[left, right]];
  while (stack.length > 0) {
    const pair = arrayPop(stack);
    const leftValue = pair[0];
    const rightValue = pair[1];
    if (leftValue === rightValue) continue;
    if (
      leftValue === null ||
      rightValue === null ||
      typeof leftValue !== typeof rightValue ||
      typeof leftValue !== "object"
    ) {
      return false;
    }

    const leftIsArray = arrayIsArray(leftValue);
    if (leftIsArray !== arrayIsArray(rightValue)) return false;
    if (leftIsArray) {
      const leftLength = objectGetOwnPropertyDescriptor(leftValue, "length")?.value;
      const rightLength = objectGetOwnPropertyDescriptor(rightValue, "length")?.value;
      if (!numberIsSafeInteger(leftLength) || leftLength !== rightLength) return false;
      for (let index = 0; index < leftLength; index += 1) {
        const leftDescriptor = objectGetOwnPropertyDescriptor(
          leftValue,
          NativeString(index),
        );
        const rightDescriptor = objectGetOwnPropertyDescriptor(
          rightValue,
          NativeString(index),
        );
        if (
          !leftDescriptor?.enumerable ||
          !rightDescriptor?.enumerable ||
          !objectHasOwn(leftDescriptor, "value") ||
          !objectHasOwn(rightDescriptor, "value")
        ) {
          return false;
        }
        arrayPush(stack, [leftDescriptor.value, rightDescriptor.value]);
      }
      continue;
    }

    const leftKeys = objectKeys(leftValue);
    const rightKeys = objectKeys(rightValue);
    if (leftKeys.length !== rightKeys.length) return false;
    for (const key of leftKeys) {
      if (!objectHasOwn(rightValue, key)) return false;
      const leftDescriptor = objectGetOwnPropertyDescriptor(leftValue, key);
      const rightDescriptor = objectGetOwnPropertyDescriptor(rightValue, key);
      if (
        !leftDescriptor?.enumerable ||
        !rightDescriptor?.enumerable ||
        !objectHasOwn(leftDescriptor, "value") ||
        !objectHasOwn(rightDescriptor, "value")
      ) {
        return false;
      }
      arrayPush(stack, [leftDescriptor.value, rightDescriptor.value]);
    }
  }

  return true;
}

function validateExecutionRequest(request, limitOverrides) {
  try {
    return validateExecutionRequestInternal(request, limitOverrides);
  } catch {
    return ["코드 실행 요청을 안전하게 검증할 수 없습니다."];
  }
}

function assertValidExecutionRequest(request, limitOverrides) {
  const errors = validateExecutionRequest(request, limitOverrides);
  if (errors.length > 0) {
    throw new NativeError(`코드 실행 요청 검증 실패:\n- ${arrayJoin(errors, "\n- ")}`);
  }
  return request;
}

function createExecutionRequestSnapshot(request, limitOverrides) {
  assertValidExecutionRequest(request, limitOverrides);

  let snapshot;
  try {
    snapshot = cloneJsonValueFromDescriptors(
      request,
      "코드 실행 요청",
      new NativeWeakMap(),
      new NativeWeakSet(),
      true,
      false,
    );
  } catch (error) {
    let message = "요청을 안전하게 복제할 수 없습니다.";
    try {
      if (typeof error?.message === "string") message = error.message;
    } catch {
      // Proxy traps may throw values whose properties cannot be inspected.
    }
    throw new NativeError(`코드 실행 요청 스냅샷 복제 실패: ${message}`);
  }

  const snapshotErrors = validateExecutionRequest(snapshot, limitOverrides);
  if (snapshotErrors.length > 0) {
    throw new NativeError(
      `코드 실행 요청 스냅샷 재검증 실패:\n- ${arrayJoin(snapshotErrors, "\n- ")}`,
    );
  }

  return deepFreezeDescriptorValue(snapshot);
}

function summarizeTestResults(testResults) {
  if (!arrayIsArray(testResults)) {
    throw new NativeTypeError("요약할 테스트 결과 배열이 필요합니다.");
  }

  const counts = {};
  for (let index = 0; index < OUTCOME_NAMES.length; index += 1) {
    defineDataProperty(counts, OUTCOME_NAMES[index], 0);
  }
  for (let index = 0; index < testResults.length; index += 1) {
    const result = testResults[index];
    if (!isPlainRecord(result) || !setHas(OUTCOME_VALUES, result.outcome)) {
      throw new NativeTypeError(`testResults[${index}].outcome이 올바르지 않습니다.`);
    }
    counts[result.outcome] += 1;
  }

  let outcome = testResults.length === 0 ? GRADING_OUTCOMES.NOT_RUN : GRADING_OUTCOMES.PASSED;
  for (let index = 0; index < OVERALL_OUTCOME_PRIORITY.length; index += 1) {
    const candidate = OVERALL_OUTCOME_PRIORITY[index];
    if (counts[candidate] > 0) {
      outcome = candidate;
      break;
    }
  }

  return {
    outcome,
    total: testResults.length,
    passed: counts.passed,
    wrong_answer: counts.wrong_answer,
    syntax_error: counts.syntax_error,
    runtime_error: counts.runtime_error,
    timeout: counts.timeout,
    output_limit: counts.output_limit,
    cancelled: counts.cancelled,
    engine_error: counts.engine_error,
    not_run: counts.not_run,
  };
}
return { serializedJsonByteLength };
})();
const { executeJavaScriptTest } = (() => {

const trustedGlobal = globalThis;
const NativeError = Error;
const NativeEval = eval;
const NativeFunction = Function;
const NativePromise = Promise;
const NativeReferenceError = ReferenceError;
const NativeString = String;
const NativeSyntaxError = SyntaxError;
const NativeTextEncoder = TextEncoder;
const NativeTypeError = TypeError;
const NativeWeakMap = WeakMap;
const NativeWeakSet = WeakSet;
const nativeObjectPrototype = Object.prototype;
const uncurryThis = (method) => Function.prototype.call.bind(method);
const arrayIsArray = Array.isArray.bind(Array);
const functionHasInstance = uncurryThis(Function.prototype[Symbol.hasInstance]);
const jsonParse = JSON.parse.bind(JSON);
const jsonStringify = JSON.stringify.bind(JSON);
const numberIsFinite = Number.isFinite.bind(Number);
const numberIsSafeInteger = Number.isSafeInteger.bind(Number);
const objectCreate = Object.create.bind(Object);
const objectDefineProperty = Object.defineProperty.bind(Object);
const objectFreeze = Object.freeze.bind(Object);
const objectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor.bind(Object);
const objectGetOwnPropertySymbols = Object.getOwnPropertySymbols.bind(Object);
const objectGetPrototypeOf = Object.getPrototypeOf.bind(Object);
const objectHasOwn = Object.hasOwn.bind(Object);
const objectKeys = Object.keys.bind(Object);
const objectPropertyIsEnumerable = uncurryThis(Object.prototype.propertyIsEnumerable);
const objectSetPrototypeOf = Object.setPrototypeOf.bind(Object);
const promiseThen = uncurryThis(Promise.prototype.then);
const reflectApply = Reflect.apply.bind(Reflect);
const reflectDeleteProperty = Reflect.deleteProperty.bind(Reflect);
const regexpTest = uncurryThis(RegExp.prototype.test);
const stringCharCodeAt = uncurryThis(String.prototype.charCodeAt);
const stringSlice = uncurryThis(String.prototype.slice);
const stringTrim = uncurryThis(String.prototype.trim);
const weakSetAdd = uncurryThis(WeakSet.prototype.add);
const weakSetDelete = uncurryThis(WeakSet.prototype.delete);
const weakSetHas = uncurryThis(WeakSet.prototype.has);
const weakMapGet = uncurryThis(WeakMap.prototype.get);
const weakMapHas = uncurryThis(WeakMap.prototype.has);
const weakMapSet = uncurryThis(WeakMap.prototype.set);
const textEncoder = new NativeTextEncoder();
const encodeText = NativeTextEncoder.prototype.encode.bind(textEncoder);
const typedArrayPrototype = objectGetPrototypeOf(Uint8Array.prototype);
const typedArrayByteLength = uncurryThis(
  objectGetOwnPropertyDescriptor(typedArrayPrototype, "byteLength").get,
);
const cloneStructuredValue =
  typeof trustedGlobal.structuredClone === "function"
    ? trustedGlobal.structuredClone.bind(trustedGlobal)
    : null;

const DEFAULT_LIMITS = objectFreeze({
  maxConsoleEntries: 100,
  maxConsoleBytes: 8 * 1024,
  maxOutputBytes: 16 * 1024,
  maxErrorMessageBytes: 1024,
});

const ERROR_NAME_MAX_BYTES = 80;
// 루트 컨테이너를 깊이 0으로 세며, 0..511의 컨테이너를 허용한다.
// code-grading.js의 요청 JSON 검사와 같은 경계여야 한다.
const MAX_JSON_CONTAINER_DEPTH = 512;
const outputLimitErrors = new NativeWeakSet();

function createDataDescriptor(value, enumerable, configurable, writable) {
  const descriptor = objectCreate(null);
  descriptor.value = value;
  descriptor.enumerable = enumerable;
  descriptor.configurable = configurable;
  descriptor.writable = writable;
  return descriptor;
}

function defineDataProperty(
  target,
  key,
  value,
  enumerable = true,
  configurable = true,
  writable = true,
) {
  return objectDefineProperty(
    target,
    key,
    createDataDescriptor(value, enumerable, configurable, writable),
  );
}

function clonePropertyDescriptor(descriptor) {
  if (!descriptor) return descriptor;
  const clone = objectCreate(null);
  const fields = ["value", "writable", "get", "set", "enumerable", "configurable"];
  for (let index = 0; index < fields.length; index += 1) {
    const field = fields[index];
    if (objectHasOwn(descriptor, field)) clone[field] = descriptor[field];
  }
  return clone;
}

class OutputLimitError extends NativeError {
  constructor(kind, message, learnerMessage, details = {}) {
    super(message);
    defineDataProperty(this, "name", "OutputLimitError");
    defineDataProperty(this, "kind", kind);
    defineDataProperty(this, "learnerMessage", learnerMessage);
    defineDataProperty(this, "details", objectFreeze({ ...details }));
    weakSetAdd(outputLimitErrors, this);
    objectFreeze(this);
  }
}

function byteLength(value) {
  return typedArrayByteLength(encodeText(value));
}

function clipUtf8(value, maxBytes) {
  const text = NativeString(value);
  if (maxBytes <= 0) {
    return { text: "", truncated: text.length > 0 };
  }

  let bytes = 0;
  let clipped = "";
  for (let index = 0; index < text.length; ) {
    const firstCodeUnit = stringCharCodeAt(text, index);
    const isSurrogatePair =
      firstCodeUnit >= 0xd800 &&
      firstCodeUnit <= 0xdbff &&
      index + 1 < text.length &&
      stringCharCodeAt(text, index + 1) >= 0xdc00 &&
      stringCharCodeAt(text, index + 1) <= 0xdfff;
    const width = isSurrogatePair ? 2 : 1;
    const character = stringSlice(text, index, index + width);
    const characterBytes = byteLength(character);
    if (bytes + characterBytes > maxBytes) {
      return { text: clipped, truncated: true };
    }
    clipped += character;
    bytes += characterBytes;
    index += width;
  }
  return { text: clipped, truncated: false };
}

function clipWithEllipsis(value, maxBytes) {
  const text = NativeString(value);
  const direct = clipUtf8(text, maxBytes);
  if (!direct.truncated) return direct.text;

  const ellipsis = "…";
  const ellipsisBytes = byteLength(ellipsis);
  if (maxBytes < ellipsisBytes) {
    return direct.text;
  }
  return `${clipUtf8(text, maxBytes - ellipsisBytes).text}${ellipsis}`;
}

function normalizeLimit(value, fallback) {
  return numberIsSafeInteger(value) && value >= 0 ? value : fallback;
}

function normalizeLimits(limits) {
  const candidate = limits && typeof limits === "object" ? limits : {};
  return {
    maxConsoleEntries: normalizeLimit(
      candidate.maxConsoleEntries,
      DEFAULT_LIMITS.maxConsoleEntries,
    ),
    maxConsoleBytes: normalizeLimit(
      candidate.maxConsoleBytes,
      DEFAULT_LIMITS.maxConsoleBytes,
    ),
    maxOutputBytes: normalizeLimit(candidate.maxOutputBytes, DEFAULT_LIMITS.maxOutputBytes),
    maxErrorMessageBytes: normalizeLimit(
      candidate.maxErrorMessageBytes,
      DEFAULT_LIMITS.maxErrorMessageBytes,
    ),
  };
}

function safelyReadErrorField(error, field) {
  try {
    return error?.[field];
  } catch {
    return undefined;
  }
}

function errorName(error) {
  const candidate = safelyReadErrorField(error, "name");
  const name = typeof candidate === "string" && stringTrim(candidate) ? candidate : "Error";
  return clipWithEllipsis(name, ERROR_NAME_MAX_BYTES);
}

function errorMessage(error) {
  const candidate = safelyReadErrorField(error, "message");
  if (typeof candidate === "string") return candidate;
  if (typeof error === "string") return error;
  if (error === null) return "null 값이 오류로 전달되었습니다.";
  if (error === undefined) return "undefined 값이 오류로 전달되었습니다.";

  try {
    return NativeString(error);
  } catch {
    return "오류 내용을 문자열로 표시할 수 없습니다.";
  }
}

function learnerMessageFor(outcome, name) {
  if (outcome === "syntax_error") {
    return "코드 문법을 해석하지 못했습니다. 괄호, 따옴표와 키워드 사용을 확인해 보세요.";
  }
  if (outcome === "engine_error") {
    if (name === "InputError") {
      return "테스트 입력을 안전하게 준비하지 못했습니다. 입력값이 JSON 호환 형식과 깊이 제한을 지키는지 확인해 주세요.";
    }
    return "현재 브라우저 설정에서는 코드 실행기를 시작할 수 없습니다. 동적 코드 실행 정책을 확인해 주세요.";
  }
  if (name === "ReferenceError") {
    return "실행할 함수를 찾지 못했거나 선언되지 않은 이름을 사용했습니다. 함수 이름과 변수 선언을 확인해 보세요.";
  }
  if (name === "TypeError") {
    return "실행 중 값의 종류가 맞지 않아 작업을 계속하지 못했습니다. 함수 호출과 값의 형태를 확인해 보세요.";
  }
  if (name === "RangeError") {
    return "실행 중 허용할 수 있는 값의 범위를 벗어났습니다. 반복 횟수와 입력값의 크기를 확인해 보세요.";
  }
  return "코드를 실행하는 중 오류가 발생했습니다. 오류 메시지와 해당 줄 주변을 확인해 보세요.";
}

function isInstanceOf(constructor, value) {
  try {
    return functionHasInstance(constructor, value);
  } catch {
    return false;
  }
}

function isOutputLimitError(error) {
  try {
    return weakSetHas(outputLimitErrors, error);
  } catch {
    return false;
  }
}

function describeError(error, outcome, maxMessageBytes) {
  const name = errorName(error);
  return {
    name,
    message: clipWithEllipsis(errorMessage(error), maxMessageBytes),
    learnerMessage: clipWithEllipsis(
      learnerMessageFor(outcome, name),
      maxMessageBytes,
    ),
  };
}

function consoleByteLimitError(limits) {
  return new OutputLimitError(
    "console_bytes",
    `콘솔 출력 크기가 ${limits.maxConsoleBytes}바이트를 넘었습니다.`,
    "콘솔 출력이 너무 깁니다. 출력할 값과 console 호출 횟수를 줄여 보세요.",
    { maxConsoleBytes: limits.maxConsoleBytes },
  );
}

function previewTextParts(parts, maxBytes) {
  let text = "";
  let remainingBytes = maxBytes;

  for (let index = 0; index < parts.length; index += 1) {
    const clipped = clipUtf8(parts[index], remainingBytes);
    text += clipped.text;
    remainingBytes -= byteLength(clipped.text);
    if (clipped.truncated) return { text, truncated: true };
  }

  return { text, truncated: false };
}

function previewValue(value, maxBytes, limits) {
  if (typeof value === "string") return clipUtf8(value, maxBytes);
  if (typeof value === "undefined") return clipUtf8("undefined", maxBytes);
  if (typeof value === "bigint") {
    return previewTextParts([NativeString(value), "n"], maxBytes);
  }
  if (typeof value === "symbol") return clipUtf8(NativeString(value), maxBytes);
  if (typeof value === "function") {
    const name = safelyReadErrorField(value, "name");
    return previewTextParts(
      typeof name === "string" && name
        ? ["[Function: ", name, "]"]
        : ["[Function]"],
      maxBytes,
    );
  }
  if (isInstanceOf(NativeError, value)) {
    return previewTextParts(
      [errorName(value), ": ", errorMessage(value)],
      maxBytes,
    );
  }

  if (value && typeof value === "object") {
    try {
      const measuredBytes = serializedJsonByteLength(value, maxBytes);
      if (measuredBytes !== null && measuredBytes > maxBytes) {
        throw consoleByteLimitError(limits);
      }
      const normalized = normalizeJsonValue(value);
      const normalizedBytes = serializedJsonByteLength(normalized, maxBytes);
      if (normalizedBytes !== null && normalizedBytes > maxBytes) {
        throw consoleByteLimitError(limits);
      }
      const serialized = jsonStringify(normalized);
      return clipUtf8(serialized ?? NativeString(value), maxBytes);
    } catch (error) {
      if (isOutputLimitError(error) && error.kind === "console_bytes") throw error;
      return clipUtf8("[표시할 수 없는 값]", maxBytes);
    }
  }

  return clipUtf8(NativeString(value), maxBytes);
}

function previewArguments(values, maxBytes, limits) {
  let preview = "";
  let remainingBytes = maxBytes;

  for (let index = 0; index < values.length; index += 1) {
    if (index > 0) {
      const separator = clipUtf8(" ", remainingBytes);
      preview += separator.text;
      remainingBytes -= byteLength(separator.text);
      if (separator.truncated) return { text: preview, truncated: true };
    }

    const valuePreview = previewValue(values[index], remainingBytes, limits);
    preview += valuePreview.text;
    remainingBytes -= byteLength(valuePreview.text);
    if (valuePreview.truncated) return { text: preview, truncated: true };
  }

  return { text: preview, truncated: false };
}

function createConsoleCapture(limits) {
  const entries = [];
  let usedBytes = 0;
  let exceeded = null;

  const capture = (method, values) => {
    if (exceeded) throw exceeded;
    if (entries.length >= limits.maxConsoleEntries) {
      exceeded = new OutputLimitError(
        "console_entries",
        `콘솔 출력 횟수가 ${limits.maxConsoleEntries}회를 넘었습니다.`,
        "콘솔 출력이 너무 많습니다. 반복문과 console 호출 횟수를 확인해 보세요.",
        { maxConsoleEntries: limits.maxConsoleEntries },
      );
      throw exceeded;
    }

    const remaining = limits.maxConsoleBytes - usedBytes;
    const remainingBytes = remaining > 0 ? remaining : 0;
    let renderedPreview;
    try {
      renderedPreview = previewArguments(values, remainingBytes, limits);
    } catch (error) {
      if (isOutputLimitError(error) && error.kind === "console_bytes") {
        exceeded = error;
      }
      throw error;
    }
    defineDataProperty(entries, entries.length, {
      method,
      preview: renderedPreview.text,
    });
    usedBytes += byteLength(renderedPreview.text);

    if (renderedPreview.truncated) {
      exceeded = consoleByteLimitError(limits);
      throw exceeded;
    }
  };

  const capturedConsole = objectCreate(null);
  for (const method of ["log", "info", "warn", "error"]) {
    defineDataProperty(
      capturedConsole,
      method,
      (...values) => capture(method, values),
      true,
      false,
      false,
    );
  }
  objectFreeze(capturedConsole);

  return {
    console: capturedConsole,
    get entries() {
      const snapshot = [];
      for (let index = 0; index < entries.length; index += 1) {
        defineDataProperty(snapshot, index, { ...entries[index] });
      }
      return snapshot;
    },
    get exceeded() {
      return exceeded;
    },
  };
}

function installGlobalConsole(capturedConsole, lockGlobalConsole) {
  const originalDescriptor = clonePropertyDescriptor(
    objectGetOwnPropertyDescriptor(trustedGlobal, "console"),
  );
  try {
    defineDataProperty(
      trustedGlobal,
      "console",
      capturedConsole,
      originalDescriptor?.enumerable ?? true,
      !lockGlobalConsole,
      false,
    );
  } catch (error) {
    return { installed: false, error, restore() {} };
  }

  return {
    installed: true,
    restore() {
      if (lockGlobalConsole) return;
      try {
        if (originalDescriptor) objectDefineProperty(trustedGlobal, "console", originalDescriptor);
        else reflectDeleteProperty(trustedGlobal, "console");
      } catch {
        // Direct test/runtime callers should discard the realm if learner code
        // deliberately makes the temporary property non-configurable.
      }
    },
  };
}

function createProtocolRecord(fields) {
  objectSetPrototypeOf(fields, null);
  return fields;
}

function observeNativePromise(value) {
  if (value === null || (typeof value !== "object" && typeof value !== "function")) {
    return null;
  }

  let resolveObservation;
  const observation = new NativePromise((resolve) => {
    resolveObservation = resolve;
  });
  defineDataProperty(observation, "constructor", NativePromise, false, false, false);

  try {
    promiseThen(
      value,
      (fulfilledValue) => {
        resolveObservation(
          createProtocolRecord({ fulfilled: true, value: fulfilledValue }),
        );
      },
      (rejection) => {
        resolveObservation(createProtocolRecord({ fulfilled: false, error: rejection }));
      },
    );
  } catch {
    return null;
  }

  return observation;
}

function outputLimitResult(error, consoleEntries, limits) {
  return createProtocolRecord({
    outcome: "output_limit",
    error: {
      name: error.name,
      message: clipWithEllipsis(error.message, limits.maxErrorMessageBytes),
      learnerMessage: clipWithEllipsis(
        error.learnerMessage,
        limits.maxErrorMessageBytes,
      ),
    },
    limit: { kind: error.kind, ...error.details },
    console: consoleEntries,
  });
}

function unsupportedReturnValue(reason) {
  return new OutputLimitError(
    "return_value",
    `반환값을 채점 가능한 형태로 변환하지 못했습니다: ${reason}`,
    "반환값은 순환이 없는 JSON 호환 값이어야 합니다. undefined, 함수, Symbol, BigInt, NaN과 Infinity는 반환할 수 없습니다.",
  );
}

function normalizeJsonValue(
  value,
  ancestors = new NativeWeakSet(),
  copies = new NativeWeakMap(),
  depth = 0,
) {
  if (value === null || typeof value === "string" || typeof value === "boolean") {
    return value;
  }
  if (typeof value === "number") {
    if (!numberIsFinite(value)) throw unsupportedReturnValue("유한하지 않은 숫자입니다.");
    return value;
  }
  const valueType = typeof value;
  if (
    valueType === "undefined" ||
    valueType === "bigint" ||
    valueType === "symbol" ||
    valueType === "function"
  ) {
    throw unsupportedReturnValue(`${typeof value} 형식은 JSON으로 표현할 수 없습니다.`);
  }
  if (depth >= MAX_JSON_CONTAINER_DEPTH) {
    throw unsupportedReturnValue("반환값이 지나치게 깊게 중첩되어 있습니다.");
  }
  if (weakSetHas(ancestors, value)) {
    throw unsupportedReturnValue("반환값이 순환 참조를 포함합니다.");
  }
  if (weakMapHas(copies, value)) return weakMapGet(copies, value);

  weakSetAdd(ancestors, value);
  try {
    if (arrayIsArray(value)) {
      const normalized = [];
      objectSetPrototypeOf(normalized, null);
      weakMapSet(copies, value, normalized);
      const lengthDescriptor = objectGetOwnPropertyDescriptor(value, "length");
      const length = lengthDescriptor?.value;
      if (!numberIsSafeInteger(length) || length < 0 || length > 0xffff_ffff) {
        throw unsupportedReturnValue("배열의 length를 안전하게 확인할 수 없습니다.");
      }
      for (let index = 0; index < length; index += 1) {
        if (!objectHasOwn(value, index)) {
          throw unsupportedReturnValue("배열의 빈 항목은 JSON 호환 반환값으로 사용할 수 없습니다.");
        }
        const descriptor = objectGetOwnPropertyDescriptor(value, NativeString(index));
        if (!descriptor || !objectHasOwn(descriptor, "value")) {
          throw unsupportedReturnValue("getter 또는 setter가 있는 배열은 반환할 수 없습니다.");
        }
        defineDataProperty(
          normalized,
          index,
          normalizeJsonValue(descriptor.value, ancestors, copies, depth + 1),
        );
      }
      return normalized;
    }

    const prototype = objectGetPrototypeOf(value);
    if (prototype !== nativeObjectPrototype && prototype !== null) {
      throw unsupportedReturnValue("일반 객체와 배열만 반환할 수 있습니다.");
    }
    const symbols = objectGetOwnPropertySymbols(value);
    for (let index = 0; index < symbols.length; index += 1) {
      if (objectPropertyIsEnumerable(value, symbols[index])) {
        throw unsupportedReturnValue("Symbol 키는 JSON으로 표현할 수 없습니다.");
      }
    }

    const normalized = objectCreate(null);
    weakMapSet(copies, value, normalized);
    const keys = objectKeys(value);
    for (let index = 0; index < keys.length; index += 1) {
      const key = keys[index];
      const descriptor = objectGetOwnPropertyDescriptor(value, key);
      if (!descriptor || !objectHasOwn(descriptor, "value")) {
        throw unsupportedReturnValue("getter 또는 setter가 있는 객체는 반환할 수 없습니다.");
      }
      defineDataProperty(
        normalized,
        key,
        normalizeJsonValue(descriptor.value, ancestors, copies, depth + 1),
      );
    }
    return normalized;
  } catch (error) {
    if (isOutputLimitError(error)) throw error;
    throw unsupportedReturnValue("객체 속성을 안전하게 읽을 수 없습니다.");
  } finally {
    weakSetDelete(ancestors, value);
  }
}

function normalizeReturnValue(value, limits) {
  const measuredBytes = serializedJsonByteLength(value, limits.maxOutputBytes);
  if (measuredBytes === null) {
    throw unsupportedReturnValue(
      "반환값이 JSON 호환 형식이 아니거나 지나치게 깊게 중첩되어 있습니다.",
    );
  }
  if (measuredBytes !== null && measuredBytes > limits.maxOutputBytes) {
    throw new OutputLimitError(
      "return_bytes",
      `반환값 크기가 ${limits.maxOutputBytes}바이트를 넘었습니다.`,
      "반환값이 너무 큽니다. 문제에서 요구한 값만 반환하도록 코드와 자료 구조를 확인해 보세요.",
      { maxOutputBytes: limits.maxOutputBytes },
    );
  }

  const normalized = normalizeJsonValue(value);
  const normalizedBytes = serializedJsonByteLength(
    normalized,
    limits.maxOutputBytes,
  );
  if (normalizedBytes === null) {
    throw unsupportedReturnValue("정규화한 반환값을 안전하게 검사하지 못했습니다.");
  }
  if (normalizedBytes > limits.maxOutputBytes) {
    throw new OutputLimitError(
      "return_bytes",
      `반환값 크기가 ${limits.maxOutputBytes}바이트를 넘었습니다.`,
      "반환값이 너무 큽니다. 문제에서 요구한 값만 반환하도록 코드와 자료 구조를 확인해 보세요.",
      { maxOutputBytes: limits.maxOutputBytes },
    );
  }

  let serialized;
  try {
    serialized = jsonStringify(normalized);
  } catch {
    throw unsupportedReturnValue("JSON 직렬화에 실패했습니다.");
  }

  const outputBytes = byteLength(serialized);
  if (outputBytes > limits.maxOutputBytes) {
    throw new OutputLimitError(
      "return_bytes",
      `반환값 크기가 ${limits.maxOutputBytes}바이트를 넘었습니다.`,
      "반환값이 너무 큽니다. 문제에서 요구한 값만 반환하도록 코드와 자료 구조를 확인해 보세요.",
      { maxOutputBytes: limits.maxOutputBytes },
    );
  }
  return jsonParse(serialized);
}

function cloneArguments(args) {
  if (!arrayIsArray(args)) {
    const error = new NativeTypeError("테스트 인수(args)는 배열이어야 합니다.");
    defineDataProperty(error, "name", "InputError");
    throw error;
  }
  if (serializedJsonByteLength(args) === null) {
    const error = new NativeTypeError(
      "테스트 인수(args)가 JSON 호환 형식 또는 컨테이너 깊이 제한을 벗어났습니다.",
    );
    defineDataProperty(error, "name", "InputError");
    throw error;
  }

  try {
    if (cloneStructuredValue) {
      return cloneStructuredValue(args);
    }
    return jsonParse(jsonStringify(args));
  } catch {
    const error = new NativeTypeError("테스트 인수(args)를 안전하게 복제하지 못했습니다.");
    defineDataProperty(error, "name", "InputError");
    throw error;
  }
}

function isValidEntryPoint(entryPoint) {
  return (
    typeof entryPoint === "string" &&
    regexpTest(/^[A-Za-z_$][A-Za-z0-9_$]*$/, entryPoint)
  );
}

function resultForError(outcome, error, consoleEntries, limits) {
  return createProtocolRecord({
    outcome,
    error: describeError(error, outcome, limits.maxErrorMessageBytes),
    console: consoleEntries,
  });
}

function compileJavaScriptFunction(source, entryPoint) {
  // outer Function은 `eval` 매개변수를 허용하도록 non-strict로 두고, inner
  // strict 함수의 direct eval에는 모듈 로드 때 캡처한 native eval만 전달한다.
  // Eval은 실행 전에 전체 Script를 파싱한다. 유효한 source라면 선행 `throw 0`이
  // 학습자 코드보다 먼저 실행되고, 문법 오류라면 sentinel보다 먼저 SyntaxError가
  // 발생한다. 별도 block wrapper가 없어 source가 검사 문맥을 닫고 탈출할 수 없다.
  const syntaxParser = new NativeFunction(
    "eval",
    "candidate",
    `return (function (source) {\n` +
      `  "use strict";\n` +
      `  try {\n` +
      `    eval('"use strict";\\nthrow 0;\\n' + source);\n` +
      `  } catch (error) {\n` +
      `    if (error === 0) return;\n` +
      `    throw error;\n` +
      `  }\n` +
      `})(candidate);`,
  );
  reflectApply(syntaxParser, undefined, [NativeEval, source]);
  return new NativeFunction(
    "console",
    `"use strict";\n${source}\n; return ${entryPoint};`,
  );
}

/**
 * 브라우저 Worker 안에서 공개 테스트 하나를 실행한다.
 * 시간 제한과 실행 문맥 폐기는 Worker 어댑터가 담당한다.
 */
async function executeJavaScriptTest(request = {}, options = {}) {
  const limits = normalizeLimits(request?.limits);
  const capture = createConsoleCapture(limits);
  const source = typeof request?.source === "string" ? request.source : "";
  const entryPoint = request?.entryPoint;
  const compileFunction =
    typeof options.compileFunction === "function"
      ? options.compileFunction
      : compileJavaScriptFunction;
  const consoleBinding = installGlobalConsole(
    capture.console,
    options.lockGlobalConsole === true,
  );

  if (!consoleBinding.installed) {
    return resultForError(
      "engine_error",
      consoleBinding.error,
      capture.entries,
      limits,
    );
  }

  try {
    if (!isValidEntryPoint(entryPoint)) {
      return resultForError(
        "runtime_error",
        new NativeReferenceError("실행할 함수 이름(entryPoint)이 올바르지 않습니다."),
        capture.entries,
        limits,
      );
    }

    let factory;
    try {
      factory = compileFunction(source, entryPoint);
    } catch (error) {
      const outcome = isInstanceOf(NativeSyntaxError, error)
        ? "syntax_error"
        : "engine_error";
      return resultForError(outcome, error, capture.entries, limits);
    }

    let clonedArgs;
    try {
      clonedArgs = cloneArguments(request?.args ?? []);
    } catch (error) {
      return resultForError("engine_error", error, capture.entries, limits);
    }

    try {
      const callable = factory(capture.console);
      if (typeof callable !== "function") {
        throw new NativeReferenceError(`실행할 함수 "${entryPoint}"를 찾을 수 없습니다.`);
      }
      const invocationResult = reflectApply(callable, undefined, clonedArgs);
      const promiseObservation = observeNativePromise(invocationResult);
      let value = invocationResult;
      if (promiseObservation) {
        const settlement = await promiseObservation;
        if (!settlement.fulfilled) throw settlement.error;
        value = settlement.value;
      }

      if (capture.exceeded) {
        return outputLimitResult(capture.exceeded, capture.entries, limits);
      }

      try {
        return createProtocolRecord({
          outcome: "completed",
          value: normalizeReturnValue(value, limits),
          console: capture.entries,
        });
      } catch (error) {
        if (isOutputLimitError(error)) {
          return outputLimitResult(error, capture.entries, limits);
        }
        throw error;
      }
    } catch (error) {
      if (capture.exceeded) {
        return outputLimitResult(capture.exceeded, capture.entries, limits);
      }
      return resultForError("runtime_error", error, capture.entries, limits);
    }
  } finally {
    consoleBinding.restore();
  }
}
return { executeJavaScriptTest };
})();
(() => {

const nativeObjectPrototype = Object.prototype;
const arrayIsArray = Array.isArray.bind(Array);
const numberIsSafeInteger = Number.isSafeInteger.bind(Number);
const objectCreate = Object.create.bind(Object);
const objectDefineProperty = Object.defineProperty.bind(Object);
const objectGetOwnPropertyDescriptor = Object.getOwnPropertyDescriptor.bind(Object);
const objectGetPrototypeOf = Object.getPrototypeOf.bind(Object);
const objectHasOwn = Object.hasOwn.bind(Object);
const reflectOwnKeys = Reflect.ownKeys.bind(Reflect);

const EXECUTE_MESSAGE_FIELDS = Object.freeze([
  "type",
  "requestId",
  "testId",
  "workerToken",
  "source",
  "entryPoint",
  "args",
  "limits",
]);
const LIMIT_FIELDS = Object.freeze([
  "maxOutputBytes",
  "maxConsoleEntries",
  "maxConsoleBytes",
]);

function containsField(fields, candidate) {
  for (let index = 0; index < fields.length; index += 1) {
    if (fields[index] === candidate) return true;
  }
  return false;
}

function isPlainRecord(value) {
  if (value === null || typeof value !== "object" || arrayIsArray(value)) return false;
  try {
    const prototype = objectGetPrototypeOf(value);
    return prototype === nativeObjectPrototype || prototype === null;
  } catch {
    return false;
  }
}

function hasExactDataFields(value, expectedFields) {
  if (!isPlainRecord(value)) return false;

  let fields;
  try {
    fields = reflectOwnKeys(value);
  } catch {
    return false;
  }
  if (fields.length !== expectedFields.length) return false;

  for (let index = 0; index < fields.length; index += 1) {
    const field = fields[index];
    if (typeof field !== "string" || !containsField(expectedFields, field)) return false;
    const descriptor = objectGetOwnPropertyDescriptor(value, field);
    if (!descriptor?.enumerable || !objectHasOwn(descriptor, "value")) return false;
  }
  return true;
}

function isValidExecutionMessage(message) {
  if (!hasExactDataFields(message, EXECUTE_MESSAGE_FIELDS)) return false;
  if (
    message.type !== "execute" ||
    typeof message.requestId !== "string" ||
    message.requestId.length === 0 ||
    typeof message.testId !== "string" ||
    message.testId.length === 0 ||
    typeof message.workerToken !== "string" ||
    message.workerToken.length === 0 ||
    typeof message.source !== "string" ||
    typeof message.entryPoint !== "string" ||
    !arrayIsArray(message.args) ||
    !hasExactDataFields(message.limits, LIMIT_FIELDS)
  ) {
    return false;
  }

  for (let index = 0; index < LIMIT_FIELDS.length; index += 1) {
    const value = message.limits[LIMIT_FIELDS[index]];
    if (!numberIsSafeInteger(value) || value <= 0) return false;
  }
  return true;
}

function defineDataField(record, name, value) {
  const descriptor = objectCreate(null);
  descriptor.value = value;
  descriptor.enumerable = true;
  descriptor.configurable = true;
  descriptor.writable = true;
  objectDefineProperty(record, name, descriptor);
}

function createResultEnvelope({ requestId, testId, workerToken, result }) {
  const response = objectCreate(null);
  defineDataField(response, "type", "result");
  defineDataField(response, "requestId", requestId);
  defineDataField(response, "testId", testId);
  defineDataField(response, "workerToken", workerToken);
  defineDataField(response, "result", result);
  return response;
}

async function executeValidatedMessage(message, postResult, runtimeOptions) {
  const requestId = message.requestId;
  const testId = message.testId;
  const workerToken = message.workerToken;
  const source = message.source;
  const entryPoint = message.entryPoint;
  const args = message.args;
  const limits = message.limits;
  const result = await executeJavaScriptTest(
    { source, entryPoint, args, limits },
    runtimeOptions,
  );
  postResult(createResultEnvelope({ requestId, testId, workerToken, result }));
  return true;
}

async function handleJavaScriptRunnerMessage(
  message,
  postResult,
  runtimeOptions = {},
) {
  if (!isValidExecutionMessage(message) || typeof postResult !== "function") {
    return false;
  }
  return executeValidatedMessage(message, postResult, runtimeOptions);
}

function createOneShotJavaScriptRunner(
  postResult,
  { runtimeOptions = {}, onComplete = () => {} } = {},
) {
  let hasHandledExecution = false;

  return async (message) => {
    if (hasHandledExecution || !isValidExecutionMessage(message)) return false;
    hasHandledExecution = true;
    try {
      return await executeValidatedMessage(message, postResult, runtimeOptions);
    } finally {
      onComplete();
    }
  };
}

const workerScope = typeof self === "undefined" ? null : self;
const dedicatedWorkerScopeConstructor =
  typeof DedicatedWorkerGlobalScope === "function" ? DedicatedWorkerGlobalScope : null;
const isDedicatedWorkerScope =
  workerScope !== null &&
  dedicatedWorkerScopeConstructor !== null &&
  workerScope instanceof dedicatedWorkerScopeConstructor;

if (isDedicatedWorkerScope && typeof workerScope.addEventListener === "function") {
  const postWorkerResult = workerScope.postMessage.bind(workerScope);
  const closeWorker =
    typeof workerScope.close === "function" ? workerScope.close.bind(workerScope) : () => {};
  const handleOneShotExecution = createOneShotJavaScriptRunner(postWorkerResult, {
    runtimeOptions: { lockGlobalConsole: true },
    onComplete: closeWorker,
  });

  workerScope.addEventListener("message", (event) => {
    void handleOneShotExecution(event?.data);
  });
}
})();
})();
